services:
  trellis2:
    build: .
    container_name: trellis2
    user: "${UID}:${GID}"
    volumes:
      - ./TRELLIS.2:/workspace/TRELLIS.2
      - ./hf_cache:/workspace/cache/huggingface
      - ./triton_cache:/workspace/cache/triton
      - ./torch_cache:/workspace/cache/torch
    ports:
      - "${GRADIO_SERVER_PORT:-7860}:${GRADIO_SERVER_PORT:-7860}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      GRADIO_SERVER_NAME: ${GRADIO_SERVER_NAME:-0.0.0.0}
      GRADIO_SERVER_PORT: ${GRADIO_SERVER_PORT:-7860}
      CUDA_HOME: /usr/local/cuda-12.9
      HF_TOKEN: ${HF_TOKEN}
      ATTN_BACKEND: ${ATTN_BACKEND:-flash-attn}

      HF_HOME: /workspace/cache/huggingface
      TRITON_CACHE_DIR: /workspace/cache/triton
      TORCH_HOME: /workspace/cache/torch
    env_file:
      - .env
    working_dir: /workspace/TRELLIS.2
    tty: true
    stdin_open: true
