services:
  trellis2:
    build: .
    container_name: trellis2
    volumes:
      - ./TRELLIS.2:/workspace/TRELLIS.2:ro
      - ./hf_cache:/root/.cache/huggingface
      - ./tmp_files:/workspace/TRELLIS.2/tmp
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      GRADIO_SERVER_NAME: 0.0.0.0
      GRADIO_SERVER_PORT: 7860
      CUDA_HOME: /usr/local/cuda-12.9
      HF_TOKEN: ${HF_TOKEN}
      ATTN_BACKEND: flash-attn
    working_dir: /workspace/TRELLIS.2
    tty: true
    stdin_open: true
